<a href="https://colab.research.google.com/github/MachineLearnia/Python-Machine-Learning/blob/master/13%20-%20Numpy%20Broadcasting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 13/30 Numpy et Broadcasting

In [0]:
import numpy as np

In [3]:
A = np.ones((2, 3))
B = 3
print(A+B) # résultat 1
 
A = np.ones((2, 3))
B = np.ones((2, 1)) # B a une colonne, elle sera étendu sur les trois colonnes de A
print(A+B) # résultat 2
 
A = np.ones((2, 3))
B = np.ones((2, 2))


[[4. 4. 4.]
 [4. 4. 4.]]
[[2. 2. 2.]
 [2. 2. 2.]]
