<a href="https://colab.research.google.com/github/MachineLearnia/Python-Machine-Learning/blob/master/13%20-%20Numpy%20Broadcasting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 13: Numpy and Broadcasting

In [2]:
import numpy as np

In [3]:
A = np.ones((2, 3))
B = 3
print(A+B) # result 1

[[4. 4. 4.]
 [4. 4. 4.]]


In [6]:
B = np.ones((2, 1))
B

array([[1.],
       [1.]])

In [7]:
A = np.ones((2, 3))
B = np.ones((2, 1)) # B has one column
print(A+B) # result 2

[[2. 2. 2.]
 [2. 2. 2.]]


In [9]:
A = np.ones((2, 3))
B = np.ones((1, 3))
print(A+B) # result 3

[[2. 2. 2.]
 [2. 2. 2.]]
